site_name: Gloo Connect
pages:
    - Index: index.md
    - Introduction:
      - Introduction: introduction/introduction.md
      - Overview: introduction/overview.md
      - Architecture: introduction/architecture.md
    - Getting Started: getting-started/README.md
repo_url: https://github.com/solo-io/gloo-connect
site_author: gloo Project Authors
copyright: Â© Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'glooconnect.solo.io']
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
    version: 0.1.1
